export const menu = [
  {
    id: 1,
    title: 'ROAST DOSA ',
    category: 'breakfast',
    price: 40,
    img: 'https://img-global.cpcdn.com/recipes/e4a74dc29c1131d3/400x400cq70/photo.jpg',
    desc: `TASTY NEI DOSA WITH SAMBAR,CHUTNI , AND SOME VARIATIES OF CHUTNI ADDED `,
  },
  {
    id: 2,
    title: 'CHICKEN BRIYANI',
    category: 'lunch',
    price: 120,
    img: 'https://www.licious.in/blog/wp-content/uploads/2022/06/chicken-hyderabadi-biryani-01.jpg',
    desc: `CHICKEN BRIYANI WITH 1SERVINGS, WITH TODAY OFFER,CHILLY ADDED `,
  },
  {
    id: 3,
    title: 'ICECREAM MILKSHAKE',
    category: 'shakes',
    price: 80,
    img: 'https://hips.hearstapps.com/del.h-cdn.co/assets/15/24/1433889344-del-milkshakes-index.jpg',
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },
  {
    id: 4,
    title: 'IDLY',
    category: 'breakfast',
    price: 20.99,
    img: 'https://www.foodie-trail.com/wp-content/uploads/2020/06/251fdbc0-57f6-41c3-a976-5192391cf040.jpg',
    desc: ` YUMMY TASTY IDLY WITH SAMBAR , CHUTNI ADDED`,
  },
  {
    id: 5,
    title: 'MUTTON BRIYANI',
    category: 'lunch',
    price: 22.99,
    img: 'https://www.licious.in/blog/wp-content/uploads/2019/11/Mutton-Biryani-1-e1574922017237.jpg',
    desc: `YUMMY TASTY MUTTON BRIYANI WITH 1 SERVINGS,WITH SWEETS ADDED  `,
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'shakes',
    price: 18.99,
    img: 'https://blogscdn.thehut.net/wp-content/uploads/sites/478/2016/04/05105624/choco-malt-shake-1024x683.jpg',
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: 'PAROTA',
    category: 'breakfast',
    price: 30,
    img: 'https://c.ndtvimg.com/2021-05/tj7sdqj8_parotta_625x300_14_May_21.jpg?im=FeatureCrop,algorithm=dnn,width=1200,height=675',
    desc: `TASTY PAROTA WITH SOFT PINCHING `,
  },
  {
    id: 8,
    title: 'BEEF BRIYANI',
    category: 'lunch',
    price: 180,
    img: 'https://nishkitchen.com/wp-content/uploads/2015/03/Beef-Biryani-1B-480x360.jpg',
    desc: `BEEF BRIYANI WITH FRIED CHILLY BEEF, BY FAMOUS COOK MUSTAF BAI`,
  },
  {
    id: 9,
    title: 'quarantine buddy',
    category: 'shakes',
    price: 46.99,
    img: 'https://blogscdn.thehut.net/wp-content/uploads/sites/478/2016/04/05105624/choco-malt-shake-1024x683.jpg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 10,
    title: 'BUCKET BRIYANI',
    category: 'lunch',
    price: 840,
    img: 'https://bucketbiryani.com/wp-content/uploads/2020/02/ChickenBucket-1.jpg',
    desc: `FAMILY PACK BUCKET BRIYANI WITH 4SERVINGS`,
  },
];
